### ISSUE TITLE
Hanging on watchForTrades

### ISSUE THREAD

**Issue by Atmannen** [jankjr/avax-arbitrage-bot#1]
I see that transactions are coming in and being parsed. But after an hour or so it exits with an error.

`\avax-arbitrage-bot\node_modules\@ethersproject\logger\src.ts\index.ts:225
        const error: any = new Error(message);
                           ^
Error: underlying network changed (event="changed", network={"chainId":43114,"name":"unknown"}, detectedNetwork={"name":"homestead","chainId":1,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"}, code=NETWORK_ERROR, version=providers/5.4.5)
    at Logger.makeError (C:\Users\joaki\Documents\GitHub\avax-arbitrage-bot\node_modules\@ethersproject\logger\src.ts\index.ts:225:28)
    at JsonRpcProvider.<anonymous> (C:\Users\joaki\Documents\GitHub\avax-arbitrage-bot\node_modules\@ethersproject\providers\src.ts\base-provider.ts:835:34)
    at step (C:\Users\joaki\Documents\GitHub\avax-arbitrage-bot\node_modules\@ethersproject\providers\lib\base-provider.js:48:23)
    at Object.next (C:\Users\joaki\Documents\GitHub\avax-arbitrage-bot\node_modules\@ethersproject\providers\lib\base-provider.js:29:53)
    at fulfilled (C:\Users\joaki\Documents\GitHub\avax-arbitrage-bot\node_modules\@ethersproject\providers\lib\base-provider.js:20:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.`

Is it possible to contact you? I really like the code and would like to contribute.

**Comment by jankjr** [comment]
Hi @Atmannen.

I think this is caused by some network changes on your end. You can fix this by replacing the WebSocket providers with the standard JSONRPC providers, this will however make the bot a bit slower at reacting to on-chain changes.

Sorry for late response. I had not noticed this project got some attention. You are free to contact me on telegram @jankjr if you want some more support.
